name: CI
on: pull_request # trigger
jobs: # ci actions
  ci-job:
    runs-on: ubuntu-latest # github runner os (linux, windows, macos)
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - uses: actions/checkout@v4.0.0 # code checkout
      - run: pnpm -v
      # - run: npm run build
      # - run: npm test
