name: CI
on: pull_request # trigger
jobs: # ci actions
  ci-job:
    runs-on: ubuntu-latest # github runner os (linux, windows, macos)
    steps:
      - uses: actions/checkout@v4.0.0 # code checkout
      - run: npm ci
      - run: npm run build
      - run: npm test
